# Global configuration for Face PAM authentication system

# Sensor configuration
[camera]
# V4L2 Infrared device used for authentication ("auto" or "/dev/videoX")
ir_device = "auto"
# V4L2 RGB device used for visual user registration (Optional, used by face-pam-enroll)
rgb_device = "auto"
# Grace delay in milliseconds after turning on the camera before starting capture
# (Useful to allow the IR camera's strobe and Auto-Exposure to stabilize)
warmup_ms = 300

# Recognition Engine Parameters
[recognition]
# Minimum Cosine similarity threshold required to authorize access (0.0 to 1.0)
# - A value greater than 0.65 is more secure but may fail if you change glasses or angle
# - A value less than 0.55 is faster but increases the risk of false positives
threshold = 0.60

[models]
# Detector used to find the face (currently only supports native rustface)
detector_path = "/var/lib/tirface-pam/models/seeta_fd_frontal_v1.0.bin"

# "mobilefacenet" | "arcface" | "/absolute/path/to/model.onnx"
# You can use one of the included models or provide the exact path to a custom model.
# If you pass a custom path, the system will deduce whether to use the arcface or mobilefacenet
# architecture based on the file name.
recognizer_model = "arcface"

recognizer_backend = "openvino"
# Supported options: 
# - "openvino" 
# - "ort"


#recognizer_device only for openvino, can be setted to CPU, GPU or NPU
recognizer_device = "NPU"

[daemon]
auth_timeout_sec = 2
# Secure mode. If activated, captures sent during enroll_cli are encrypted
# and signed using the TPM or system keys. (true/false)
#
#This is untested right now i still have to validate it.
secure_enclave = false
