use std::ffi::CStr;

pub const PAM_SUCCESS: libc::c_int = 0;
pub const PAM_USER_UNKNOWN: libc::c_int = 10;
pub const PAM_IGNORE: libc::c_int = 25;

#[repr(C)]
pub struct pam_handle_t {
    _private: [u8; 0],
}

#[link(name = "pam")]
unsafe extern "C" {
    pub fn pam_get_user(
        pamh: *const pam_handle_t,
        user: *mut *const libc::c_char,
        prompt: *const libc::c_char,
    ) -> libc::c_int;
}

pub unsafe fn get_user(pamh: *const pam_handle_t) -> Result<String, libc::c_int> {
    let mut user_ptr: *const libc::c_char = std::ptr::null();
    let res = unsafe { pam_get_user(pamh, &mut user_ptr, std::ptr::null()) };
    if res != PAM_SUCCESS || user_ptr.is_null() {
        return Err(if res == PAM_SUCCESS { PAM_USER_UNKNOWN } else { res });
    }
    let user_cstr = unsafe { CStr::from_ptr(user_ptr) };
    Ok(user_cstr.to_string_lossy().into_owned())
}

// zbus Proxy definition
#[zbus::proxy(
    interface = "org.freedesktop.TirfacePam1",
    default_service = "org.freedesktop.TirfacePam1",
    default_path = "/org/freedesktop/TirfacePam1"
)]
trait TirfacePam {
    async fn verify(&self, user: &str) -> zbus::Result<bool>;
}

#[unsafe(no_mangle)]
pub unsafe extern "C" fn pam_sm_authenticate(
    pamh: *mut pam_handle_t,
    _flags: libc::c_int,
    _argc: libc::c_int,
    _argv: *const *const libc::c_char,
) -> libc::c_int {
    // Wrap in catch_unwind to prevent unwinding panic over FFI boundary
    let result = std::panic::catch_unwind(|| {
        let mut user = match unsafe { get_user(pamh) } {
            Ok(u) => u,
            Err(err) => return err,
        };

        // Sanitize username
        user.retain(|c| !c.is_control());

        // Connect to system D-Bus
        let conn = match zbus::blocking::Connection::system() {
            Ok(c) => c,
            Err(_) => {
                // If D-Bus is unavailable or the daemon is down, fallback to password authentication
                return PAM_IGNORE;
            }
        };

        // Instanciate the blocking proxy generated by the macro
        let proxy = match TirfacePamProxyBlocking::new(&conn) {
            Ok(p) => p,
            Err(_) => return PAM_IGNORE,
        };

        // Perform D-Bus call to Tirface PAM Daemon
        match proxy.verify(&user) {
            Ok(true) => PAM_SUCCESS,
            _ => PAM_IGNORE,
        }
    });

    match result {
        Ok(code) => code,
        Err(_) => PAM_IGNORE,
    }
}

#[unsafe(no_mangle)]
pub unsafe extern "C" fn pam_sm_setcred(
    _pamh: *mut pam_handle_t,
    _flags: libc::c_int,
    _argc: libc::c_int,
    _argv: *const *const libc::c_char,
) -> libc::c_int {
    PAM_SUCCESS
}

#[unsafe(no_mangle)]
pub unsafe extern "C" fn pam_sm_acct_mgmt(
    _pamh: *mut pam_handle_t,
    _flags: libc::c_int,
    _argc: libc::c_int,
    _argv: *const *const libc::c_char,
) -> libc::c_int {
    PAM_IGNORE
}

#[unsafe(no_mangle)]
pub unsafe extern "C" fn pam_sm_open_session(
    _pamh: *mut pam_handle_t,
    _flags: libc::c_int,
    _argc: libc::c_int,
    _argv: *const *const libc::c_char,
) -> libc::c_int {
    PAM_IGNORE
}

#[unsafe(no_mangle)]
pub unsafe extern "C" fn pam_sm_close_session(
    _pamh: *mut pam_handle_t,
    _flags: libc::c_int,
    _argc: libc::c_int,
    _argv: *const *const libc::c_char,
) -> libc::c_int {
    PAM_IGNORE
}

#[unsafe(no_mangle)]
pub unsafe extern "C" fn pam_sm_chauthtok(
    _pamh: *mut pam_handle_t,
    _flags: libc::c_int,
    _argc: libc::c_int,
    _argv: *const *const libc::c_char,
) -> libc::c_int {
    PAM_IGNORE
}
